name: side_effect_cubit
description: >
  "An extension to the bloc state management library which serve an additional stream 
  for events that should be consumed only once"
version: 1.0.1
homepage: https://github.com/kevinarch/side_effect_cubit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.0.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
