name: side_effect_cubit_test
description: This is a testing utility designed to simplify the process of testing Blocs that produce side effects. It builds upon the bloc_test package and introduces features that allow developers to expect side effects to be emitted
repository: https://github.com/kevinarch/side_effect_cubit
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  side_effect_cubit: ^1.0.0
  meta: ^1.9.0
  mocktail: ">=0.2.0 <2.0.0"
  test: ^1.16.0
  diff_match_patch: ^0.4.1
  bloc: ^8.0.0

dev_dependencies:
  lints: ^3.0.0
